// Local dataset: 60 realistic Indian tech jobs
window.JOBS = [
  {
    id: "job-001",
    title: "SDE Intern",
    company: "Flipkart",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/jobs/001",
    description: "Work within a cross-functional team to build backend services. Learn e-commerce systems, microservices, and deployment practices. Ideal for students with strong CS fundamentals."
  },
  {
    id: "job-002",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/jobs/002",
    description: "Join as a trainee on enterprise projects supporting banking and insurance clients. The role includes hands-on coding, training, and mentorship over the first year."
  },
  {
    id: "job-003",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "Postgres", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/careers/003",
    description: "Contribute to payments platform features and integrations. Work on API design, database schemas, and reliability improvements. Collaboration with product and ops teams."
  },
  {
    id: "job-004",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/004",
    description: "Assist with building customer-facing UI components in React. Learn design patterns, testing, and accessibility best practices within a product team."
  },
  {
    id: "job-005",
    title: "QA Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Selenium", "Test Cases", "Manual Testing"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/005",
    description: "Support quality engineering efforts for SaaS products. Write test plans, run test suites, and report defects. Good exposure to product cycles and QA tooling."
  },
  {
    id: "job-006",
    title: "Data Analyst Intern",
    company: "CRED",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://cred.club/careers/006",
    description: "Analyze product metrics and build dashboards to inform product decisions. Work with data pipelines and collaborate with data scientists."
  },
  {
    id: "job-007",
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "REST"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://infosys.com/careers/007",
    description: "Develop and maintain enterprise Java applications. Participate in requirement analysis, unit testing, and code reviews within delivery teams."
  },
  {
    id: "job-008",
    title: "Python Developer (Fresher)",
    company: "Juspay",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "APIs", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://juspay.in/careers/008",
    description: "Work on backend services and payment integrations using Python. Collaborate with senior engineers to learn production-grade engineering practices."
  },
  {
    id: "job-009",
    title: "React Developer (1-3)",
    company: "Swiggy",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://swiggy.com/careers/009",
    description: "Build responsive web apps for customer experiences. Improve component libraries and performance, and collaborate with designers to ship features."
  },
  {
    id: "job-010",
    title: "SDE Intern",
    company: "PhonePe",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Distributed Systems", "Kubernetes"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://phonepe.com/careers/010",
    description: "Intern with backend teams to design scalable services. Learn cloud deployment and monitoring in a high-throughput payments environment."
  },
  {
    id: "job-011",
    title: "Junior Backend Developer",
    company: "Swiggy",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Go", "MySQL", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://swiggy.com/careers/011",
    description: "Join the logistics team to improve delivery routing and reliability. Work with Go services and optimize database queries for scale."
  },
  {
    id: "job-012",
    title: "Frontend Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["HTML", "CSS", "JavaScript"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/012",
    description: "Work on UI enhancements for internal tools. Learn front-end patterns and collaborate with product teams to deliver accessible interfaces."
  },
  {
    id: "job-013",
    title: "Data Analyst Intern",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Tableau", "Python"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/013",
    description: "Support operations analytics by building dashboards and models. Exposure to large datasets and automation tools used by operations teams."
  },
  {
    id: "job-014",
    title: "Java Developer (0-1)",
    company: "Cognizant",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://cognizant.com/careers/014",
    description: "Work on enterprise microservices for global clients. Good training environment and exposure to cloud-native patterns."
  },
  {
    id: "job-015",
    title: "Python Developer (Fresher)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://freshworks.com/careers/015",
    description: "Join the backend team to build customer support tools. Learn product-focused engineering with mentoring from senior developers."
  },
  {
    id: "job-016",
    title: "React Developer (1-3)",
    company: "Zoho",
    location: "Remote",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "CSS-in-JS", "Performance"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zoho.com/careers/016",
    description: "Work remotely on product UI for enterprise customers. Improve rendering performance and component reuse across products."
  },
  {
    id: "job-017",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Algorithms", "Distributed Systems"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/017",
    description: "Intern across backend teams solving performance and reliability problems. Formal mentorship and project ownership during the internship."
  },
  {
    id: "job-018",
    title: "Junior Backend Developer",
    company: "CRED",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kotlin", "Postgres", "APIs"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "10–18 LPA",
    applyUrl: "https://cred.club/careers/018",
    description: "Backend role focused on transaction systems and data integrity. Collaborate with cross-functional teams to improve product reliability."
  },
  {
    id: "job-019",
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "UX", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://swiggy.com/careers/019",
    description: "Contribute to the consumer web app with a focus on UI quality. Learn testing and instrumentation for frontend features."
  },
  {
    id: "job-020",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Statistics"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/jobs/020",
    description: "Support merchant analytics and pricing experiments. Build reports and analyses to influence product decisions."
  },
  {
    id: "job-021",
    title: "SDE Intern",
    company: "Razorpay",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Payments", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/021",
    description: "Join payments infrastructure team to work on reliability and integration. Great exposure to fintech systems and monitoring."
  },
  {
    id: "job-022",
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "SQL"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://wipro.com/careers/022",
    description: "Entry-level Java role working on enterprise applications. Training provided and rotation across projects in the first year."
  },
  {
    id: "job-023",
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/023",
    description: "Build web experiences for payments products, focusing on reliability and testability. Work closely with design and backend teams."
  },
  {
    id: "job-024",
    title: "Junior Backend Developer",
    company: "Capgemini",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "SOAP", "REST"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/024",
    description: "Work on client-facing integration projects. Good training and mentorship for early-career engineers."
  },
  {
    id: "job-025",
    title: "Frontend Intern",
    company: "Juspay",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://juspay.in/careers/025",
    description: "Work on payment flow UI and help optimize conversion funnels. Gain experience with production front-end codebases."
  },
  {
    id: "job-026",
    title: "Python Developer (Fresher)",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "APIs", "Django"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://cognizant.com/careers/026",
    description: "Work on web applications and internal tooling using Python. Training provided as part of the onboarding program."
  },
  {
    id: "job-027",
    title: "SDE Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/027",
    description: "Intern in product teams building SaaS features. Strong focus on coding fundamentals, tests, and product impact."
  },
  {
    id: "job-028",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Pandas"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/jobs/028",
    description: "Analyze merchandising and recommendation performance. Help build data products that inform merchandising decisions."
  },
  {
    id: "job-029",
    title: "Junior Backend Developer",
    company: "IBM",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Cloud", "SQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://ibm.com/careers/029",
    description: "Work on enterprise cloud solutions and integrations. Exposure to hybrid cloud deployments and client collaboration."
  },
  {
    id: "job-030",
    title: "React Developer (1-3)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://freshworks.com/careers/030",
    description: "Enhance product UI and improve performance for customer-facing dashboards. Collaborate on design systems and accessibility."
  },
  {
    id: "job-031",
    title: "SDE Intern",
    company: "PhonePe",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://phonepe.com/careers/031",
    description: "Intern on backend teams building high-scale services for payments and user management. Emphasis on observability and reliability."
  },
  {
    id: "job-032",
    title: "Java Developer (0-1)",
    company: "Oracle",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "SQL", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://oracle.com/careers/032",
    description: "Join cloud engineering teams to build enterprise features. Great foundation for early-career engineers with client-facing projects."
  },
  {
    id: "job-033",
    title: "Frontend Intern",
    company: "Jupiter (startup)",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Figma", "CSS"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://jupiter.money/careers/033",
    description: "Work on consumer banking UI and product experiments. Gain hands-on experience in startup product cycles."
  },
  {
    id: "job-034",
    title: "Data Analyst Intern",
    company: "Google (India)",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["BigQuery", "SQL", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.google.com/jobs/034",
    description: "Support data initiatives for product teams. Work with large-scale analytics and partner with engineers to create data pipelines."
  },
  {
    id: "job-035",
    title: "Junior Backend Developer",
    company: "Accenture",
    location: "Mumbai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "APIs", "SQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://accenture.com/careers/035",
    description: "Entry-level backend role working on client projects across industries. Training and mentoring provided during onboarding."
  },
  {
    id: "job-036",
    title: "React Developer (1-3)",
    company: "CRED",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://cred.club/careers/036",
    description: "Develop user interfaces for financial products. Focus on test coverage, performance, and design system integration."
  },
  {
    id: "job-037",
    title: "SDE Intern",
    company: "Swiggy",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Data Structures", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://swiggy.com/careers/037",
    description: "Intern with teams working on delivery optimization and routing. Build algorithms and systems to improve operational metrics."
  },
  {
    id: "job-038",
    title: "Junior Backend Developer",
    company: "Dell",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Cloud", "REST"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://dell.com/careers/038",
    description: "Contribute to enterprise product features and integrations. Learn cloud deployment and client interaction processes."
  },
  {
    id: "job-039",
    title: "Python Developer (Fresher)",
    company: "Juspay",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Flask", "SQL"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://juspay.in/careers/039",
    description: "Backend development focused on payment integrations. Work closely with senior engineers to ship reliable services."
  },
  {
    id: "job-040",
    title: "React Developer (1-3)",
    company: "Zoho",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Performance", "UI"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zoho.com/careers/040",
    description: "Work on UI improvements and performance tuning for enterprise applications. Collaborate with cross-product teams to deliver features."
  },
  {
    id: "job-041",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Looker", "Python"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/jobs/041",
    description: "Work on analytics for supply chain and logistics. Build dashboards and models to support operational decisions."
  },
  {
    id: "job-042",
    title: "Junior Backend Developer",
    company: "SAP",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "ABAP", "SQL"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://sap.com/careers/042",
    description: "Develop features for enterprise software. Work with legacy systems and learn about enterprise-grade testing and deployment."
  },
  {
    id: "job-043",
    title: "SDE Intern",
    company: "Razorpay",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Payments", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/043",
    description: "Intern on payment infrastructure and event-driven systems. Learn about reliability and high-throughput processing."
  },
  {
    id: "job-044",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Remote",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/044",
    description: "Remote internship focused on UI component development and accessibility improvements. Great for developers starting their frontend careers."
  },
  {
    id: "job-045",
    title: "Python Developer (Fresher)",
    company: "StartUp Labs (startup)",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Docker", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://startuplabs.example/jobs/045",
    description: "Early-stage startup role building product features in Python. High learning curve and exposure to multiple parts of the stack."
  },
  {
    id: "job-046",
    title: "Java Developer (0-1)",
    company: "HCL",
    location: "Noida",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "SQL"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://hcltech.com/careers/046",
    description: "Join delivery teams working on enterprise applications. Structured training program included for new hires."
  },
  {
    id: "job-047",
    title: "React Developer (1-3)",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Context API", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://paytm.com/careers/047",
    description: "Build customer-facing components for payments and wallets. Focus on reliability and cross-platform consistency."
  },
  {
    id: "job-048",
    title: "SDE Intern",
    company: "Oracle",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Cloud", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://oracle.com/careers/048",
    description: "Intern with cloud teams building scalable features for enterprise customers. Great mentorship and learning opportunities."
  },
  {
    id: "job-049",
    title: "Junior Backend Developer",
    company: "Capillary Technologies (startup)",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Microservices", "Kafka"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://capillary.example/jobs/049",
    description: "Work on customer engagement systems and real-time messaging features. Strong focus on scalable architectures."
  },
  {
    id: "job-050",
    title: "Data Analyst Intern",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://oracle.com/careers/050",
    description: "Support data reporting and dashboarding for internal stakeholders. Learn enterprise data tools and reporting best practices."
  },
  {
    id: "job-051",
    title: "React Developer (1-3)",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://amazon.jobs/051",
    description: "Build scalable frontend components for commerce experiences. Emphasis on performance, accessibility, and maintainability."
  },
  {
    id: "job-052",
    title: "SDE Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["JavaScript", "Node.js", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/052",
    description: "Intern on product engineering teams focusing on backend services and automation. Learn testing and deployment practices."
  },
  {
    id: "job-053",
    title: "Junior Backend Developer",
    company: "Accenture",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "APIs", "SQL"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://accenture.com/careers/053",
    description: "Work on client engagements delivering backend features. Structured growth and client exposure provided."
  },
  {
    id: "job-054",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "APIs"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zoho.com/careers/054",
    description: "Work on building and maintaining REST APIs for SaaS products. Great mentorship and product-focused engineering."
  },
  {
    id: "job-055",
    title: "React Developer (1-3)",
    company: "Flipkart",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Performance"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.flipkartcareers.com/jobs/055",
    description: "Work on consumer web features improving conversion and speed. Collaborate closely with product managers and designers."
  },
  {
    id: "job-056",
    title: "SDE Intern",
    company: "StartSmart (startup)",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Node.js", "MongoDB", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://startsmart.example/jobs/056",
    description: "Intern at an early-stage startup building core product features. Fast-paced environment with broad ownership."
  },
  {
    id: "job-057",
    title: "Junior Backend Developer",
    company: "IBM",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Cloud", "APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://ibm.com/careers/057",
    description: "Work on cloud services and integrations for enterprise clients. Good exposure to distributed systems and client work."
  },
  {
    id: "job-058",
    title: "React Developer (1-3)",
    company: "CRED",
    location: "Bengaluru",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Design Systems", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://cred.club/careers/058",
    description: "Contribute to financial product UI and design system components. Emphasis on reuse, tests, and accessibility."
  },
  {
    id: "job-059",
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bengaluru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://swiggy.com/careers/059",
    description: "Assist with operational analytics and reporting. Learn to work with streaming and batch data for logistics insights."
  },
  {
    id: "job-060",
    title: "Junior Backend Developer",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "REST", "SQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/060",
    description: "Work on enterprise application development with a focus on backend services and integrations. Structured mentoring available."
  }
];

